name: p2plib_flutter
description: "A Flutter package to easy use of p2plib with mDNS support"
version: 0.1.5
homepage: https://github.com/alexandrim0/p2plib-flutter

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  sodium_libs: ^3.2.0
  sodium: ^3.2.0
  p2plib: ^2.2.2
  nsd: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
